Feature/83 password recovery system
ISPP-07/backend pull request #125
Opened 2024-03-14 18:08 UTC by Thealean28

## Description
Added a new password recovery system using 2-factor authentication. If you are logged as an user, you can obtain a qr code to obtain your recovery codes. Then, you can recover your password providing your email associated to your user and the verfication code.

## Related Issue(s)
- #83 

## Checklist
- [ ] I have read and followed the project's contributing guidelines.
- [ ] I have tested the changes locally.
- [ ] I have made corresponding changes to the documentation if necessary.
- [ ] My code follows the project's code style guidelines.

## Reviewers
- @gonzcm 

## Tester (if applicable)
- @alblopnov 

## Screenshots 
Using this endpoint, you can obtain your qr code. (Note that you need to be authenticated)
<img width="919" alt="image" src="https://github.com/ISPP-07/backend/assets/73127793/ec874dc1-4ea6-46f8-9c17-464e59994f1b">

Then, you can change your password by filling that form.
<img width="910" alt="image" src="https://github.com/ISPP-07/backend/assets/73127793/3288d5e3-e34e-44d4-b075-b4d17a00101a">

2024-03-15 19:11 UTC, gonzcm requested changes
The implementation works smoothly. Fix the changes I have mentioned to improve the quality of the code. Great job!

2024-03-15 19:15 UTC, gonzcm commented
It would be a good idea to prepare a short briefing so that frontend members understand the implementation, the password recovery flow, and have the qr displayed to the user. This will also help to know if we need to make any changes in the backend. What do you think about it?

2024-03-16 10:48 UTC, Thealean28 commented on src/modules/shared/auth/controller.py
> +            detail="Correo electrónico no encontrado"
Done

2024-03-16 10:49 UTC, Thealean28 commented on src/modules/shared/user/router.py
> +from src.modules.shared.user.model import User, UserCreate, UserOut
Done

2024-03-16 10:49 UTC, Thealean28 commented on src/modules/shared/user/router.py
> +from src.core.deps import DataBaseDep, get_current_user
Done

2024-03-16 10:49 UTC, Thealean28 commented on src/modules/shared/user/router.py
> +from fastapi import APIRouter, Depends, status
Done

2024-03-16 10:49 UTC, Thealean28 commented on src/modules/shared/auth/controller.py
> +            detail="Correo electrónico no encontrado"
Done

2024-03-16 10:49 UTC, Thealean28 commented on src/modules/shared/user/controller.py
> +            detail="El correo electrónico introducido no está asociado a ningún usuario")
Done

2024-03-16 10:49 UTC, Thealean28 commented on src/modules/shared/user/controller.py
> +            detail="El código de verificación es incorrecto"
Done

2024-03-16 16:30 UTC, gonzcm approved these changes
Well done!

2024-03-16 16:30 UTC, merged