fix: Fixed import excel products and patients #194
ISPP-07/backend pull request #195
Opened 2024-03-28 18:10 UTC by jmartinacu

## Description
Fix Import Excel of Patients and Products into db. Due to the new changes in update of base_crud.py.

## Related Issue(s)
- #194 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @alvgonfri 

## Screenshots 
<img width="809" alt="image" src="https://github.com/ISPP-07/backend/assets/99323099/8efc2acc-8997-4ca1-916d-11ac5e1e25ff">

2024-03-28 20:56 UTC, alblopnov requested changes
I requested some changes. If you could, please also change the single quoted ['id`] in line 36 of test_shared_user to fix the problem we talked about this morning

2024-03-28 20:56 UTC, alblopnov commented on src/modules/cyc/warehouse/service.py
Please, delete the duplicated method get_products_service from this service

2024-03-28 23:14 UTC, alvgonfri requested changes
The feature works great, but you should make the changes requested by @alblopnov and also another change at `helpers.py`: that string must be written entirely on a single line.

![image](https://github.com/ISPP-07/backend/assets/73192598/e45d1f29-b75a-44d9-bdf1-cb3c2ef485be)

2024-03-29 15:22 UTC, alvgonfri approved these changes
Everything has been corrected.

2024-03-29 15:32 UTC, merged