feat: Create patients call #4
ISPP-07/backend pull request #24
Opened 2024-02-22 21:45 UTC by Thealean28

2024-02-28 17:01 UTC, Thealean28 commented on src/core/database/session.py
> +WEB_CONCURRENCY = 100
Done!

2024-03-01 10:36 UTC, jmartinacu requested changes
The code is not following all the rules specified by the code style PEP8

2024-03-01 10:36 UTC, jmartinacu commented on tests/api/test_acat_patient.py
> +from src.modules.acat.patient.model import Patient
This import is not used in the file.

2024-03-01 17:10 UTC, Thealean28 commented on tests/api/test_acat_patient.py
> +from src.modules.acat.patient.model import Patient
Done!

2024-03-02 11:43 UTC, gonzcm commented on tests/api/test_acat_patient.py
> +from src.modules.acat.patient.model import Patient
Well done!

2024-03-02 11:44 UTC, gonzcm commented on src/core/database/session.py
> +    pool_size=POOL_SIZE,
Well done!

2024-03-02 11:44 UTC, gonzcm commented on src/core/database/session.py
> +WEB_CONCURRENCY = 100
Well done!

2024-03-02 11:46 UTC, gonzcm requested changes

2024-03-02 11:46 UTC, gonzcm commented on src/modules/acat/patient/router.py
> +async def create_patient(session: SessionDep, patient: Patient) -> Any:
Please add the return type of function.

2024-03-03 12:07 UTC, Thealean28 commented on src/modules/acat/patient/router.py
> +async def create_patient(session: SessionDep, patient: Patient) -> Any:
Done!

2024-03-03 19:48 UTC, alvarobernal2412 approved these changes
Thank you for resolving conflicts! This task is necessary for the correct functioning of the app.

2024-03-04 08:31 UTC, gonzcm approved these changes
Good job!

2024-03-04 08:55 UTC, merged