feat: Added API call for family creation #6
ISPP-07/backend pull request #25
Opened 2024-02-22 22:52 UTC by alvgonfri

## Description
Now it is possible to create a family through an API call.

## Related Issue(s)
- #6 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @jmartinacu 
- @davidg43 

## Screenshots
![image](https://github.com/ISPP-07/backend/assets/73192598/0acf57ff-71f5-490a-8db9-0384f3ae7909)

2024-02-26 19:35 UTC, davidg43 approved these changes
Consideration should be given to the possibility of creating a customized response for each endpoint. The tests to be carried out on this same branch are still pending.

2024-02-26 19:35 UTC, davidg43 commented on src/modules/cyc/family/router.py
Correct structure and operation in the absence of defining the type of response in this case "Any" would be replaced by Family Result Class. This will allow us to manage the exceptions.
Example: ![image](https://github.com/ISPP-07/backend/assets/80384087/3ff6732e-a116-4065-8e5b-f30b5b307bdf)

2024-02-26 21:44 UTC, alblopnov commented
@davidg43 and @jmartinacu Family creation Endpoint test was created. Please review this so that we can merge this PR to develop

2024-02-26 22:00 UTC, alvgonfri commented on src/modules/cyc/family/router.py
That must be taken into account, but as we said in the last backend meeting, we are going to refactor that code in future sprints. I think the code that is currently in this branch can be merged so that we have the first version of the API as soon as possible.

2024-02-26 22:07 UTC, davidg43 submitted a review, later dismissed

2024-02-27 17:25 UTC, jmartinacu requested changes
There are changes to be done

2024-02-27 17:25 UTC, jmartinacu commented on tests/api/test_cyc_family_creation.py
> +from src.modules.acat.patient.model import Patient
The following import is not used in the file and this is not a good practice according to the coding style agreed upon in the project.

2024-02-27 17:25 UTC, jmartinacu commented on src/modules/cyc/family/router.py
> +async def create_family(session: SessionDep, family: Family) -> Any:
The response code, code 200, returned by the endpoint is not the most appropriate for the functionalities occurring at the endpoint. It would be more appropriate to use code 201.

2024-02-27 17:25 UTC, jmartinacu commented on tests/api/test_cyc_family_creation.py
> +        "id": 1,
The endpoint will not receive the id of the family in the body. The id will be added by the db.

2024-02-27 18:21 UTC, alvgonfri commented
> There are changes to be done

Requested changes have been resolved.

2024-02-28 09:13 UTC, jmartinacu approved these changes
Everything good

2024-02-28 10:55 UTC, davidg43 approved these changes

2024-02-28 10:56 UTC, merged