Feature/5 api call for patient detail get
ISPP-07/backend pull request #26
Opened 2024-02-22 23:03 UTC by alblopnov

## Description
The objective of this feature is to implement the get endpoint of the patient details that will be used this week in the development of the application.

## Related Issue(s)
- #5  

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @Thealean28 
- @jmartinacu 

## Screenshots (if applicable)
![image](https://github.com/ISPP-07/backend/assets/74500641/b05d3607-a22e-4c72-a263-dbf5ce57ceee)

## Notes (if applicable)

2024-02-24 11:11 UTC, Thealean28 submitted a review, later dismissed
Good job!

2024-02-28 12:08 UTC, gonzcm requested changes

2024-02-28 12:08 UTC, gonzcm commented on tests/api/test_acat_patient.py
> +    assert response.status_code == 200
This PR should be reversed and revised.

2024-02-29 23:14 UTC, gonzcm requested changes

2024-02-29 23:14 UTC, gonzcm commented on migrations/env.py
This file should not be included.

2024-02-29 23:14 UTC, gonzcm commented on src/core/config.py
This changes should not be included.

2024-02-29 23:14 UTC, gonzcm commented on src/main.py
This changes should not be included.

2024-02-29 23:17 UTC, alblopnov commented on migrations/env.py
👍

2024-02-29 23:17 UTC, alblopnov commented on src/core/config.py
🥇

2024-02-29 23:18 UTC, alblopnov commented on src/main.py
fixed it already 🐐

2024-03-03 16:52 UTC, Thealean28 approved these changes
Good job! Everything is perfect.

2024-03-04 08:58 UTC, gonzcm submitted a review, later dismissed
Good job!

2024-03-04 09:15 UTC, alvarobernal2412 approved these changes
This PR is ready to merge now!

2024-03-04 09:20 UTC, jmartinacu approved these changes
Everything look fine

2024-03-04 09:21 UTC, merged