Feature/40 database schema products appointments
ISPP-07/backend pull request #41
Opened 2024-02-27 12:13 UTC by jmartinacu

## Description
Add Product and Appointment models to the db

## Related Issue(s)
- #40 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @gonzcm  
- @alvgonfri

2024-02-27 12:19 UTC, jmartinacu commented on src/modules/cyc/family/model.py
> +    type: str
This will be a field which can only be fill with the following values: "child", "adult". 
This validation will be done in the future.

2024-02-27 17:34 UTC, alvgonfri requested changes

2024-02-27 17:34 UTC, alvgonfri commented on src/modules/cyc/family/model.py
> +    persons: list[Person] = Relationship(back_populates='family')
Is it necessary to set the Person-Family relationship as bidirectional? It's better if we avoid bidirectional relationships.

2024-02-27 17:34 UTC, alvgonfri commented on src/modules/cyc/family/model.py
> +    products: list[Product] = Relationship(back_populates='warehouse')
This code must be placed in other file. This is not related with families.

2024-02-27 17:34 UTC, alvgonfri commented on src/modules/cyc/family/model.py
> +    persons: list[Person] = Relationship(back_populates='family')
This also applies to the Product-Warehouse and Obervation-Family relationships.

2024-02-27 17:34 UTC, alvgonfri commented on src/modules/cyc/family/model.py
> +# POR AHORA LO HE RELACIONADO COMO 1-* PERO PODRIA SER *-*
It's important ask this in the next NGOs meeting.

2024-02-27 18:03 UTC, jmartinacu commented on src/modules/cyc/family/model.py
> +    products: list[Product] = Relationship(back_populates='warehouse')
Ok I will change it I forgot about the directory per recourse politic.

2024-02-27 18:04 UTC, jmartinacu commented on src/modules/cyc/family/model.py
> +    persons: list[Person] = Relationship(back_populates='family')
This is not a bidirectional relationship, this is the way that sqlModel uses to manage relationships between models.

2024-02-27 18:28 UTC, alvgonfri commented on src/modules/cyc/family/model.py
> +    type: str
Don't you think we could create an enum?

2024-02-28 09:18 UTC, jmartinacu commented on src/modules/cyc/family/model.py
> +    type: str
Yes that is a better way to implement this field, I will fix it.

2024-02-28 11:43 UTC, gonzcm commented on src/modules/cyc/family/model.py
> +    type: str
The request has been successfully fulfilled. Good work to you both!

2024-02-28 11:56 UTC, gonzcm commented on src/modules/cyc/family/model.py
> +# POR AHORA LO HE RELACIONADO COMO 1-* PERO PODRIA SER *-*
It is true that the information gathered at the meeting is somewhat confusing. I have noted the question for the next meeting. If it seems right to you both, we can merge the PR so that the rest of the group can continue working and we will address this matter as soon as we receive more information.

2024-02-28 13:57 UTC, alvgonfri approved these changes
It looks correct now.

2024-02-28 14:54 UTC, gonzcm approved these changes
Great job!

2024-02-28 14:54 UTC, merged