feat: Added deatils details get endpoint #46
ISPP-07/backend pull request #54
Opened 2024-02-28 17:49 UTC by Thealean28

## Description
Now it is possible to get the details of every family stored in the database.

## Related Issue(s)
- #46 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @alvgonfri 
- @josgarber6 

## Tester
- @jmartinacu

2024-02-28 21:13 UTC, josgarber6 submitted a review, later dismissed
Everything works correctly, well done

2024-03-02 01:03 UTC, davidg43 commented
Now it is possible to test the api call for family details! Due to an unexpected failure I cant run the tests so I request a revision to run them as soon as possible.

2024-03-02 11:29 UTC, alvgonfri requested changes
- The URL must be changed to `/api/v1/cyc/family/{family_id}`. It's important to change it in the test, too:
![image](https://github.com/ISPP-07/backend/assets/73192598/03e0c522-1c82-42dd-b3a3-de3d91f6030e)

- The test is not working. Please take the test uploaded in this commit as an example of creating a family: https://github.com/ISPP-07/backend/pull/49/commits/f43f184fccb4bc98b5d26aaacfb2197c99681694. @davidg43

2024-03-03 09:31 UTC, alvgonfri requested changes
It's better now, but there are still some problems in the tests. @davidg43 

Also, the URL must be changed as indicated in my previous comment.

2024-03-03 09:31 UTC, alvgonfri commented on tests/api/test_cyc_family_details.py
> +    family_id = create_family["id"]
Change to `create_family.id`

2024-03-03 09:31 UTC, alvgonfri commented on tests/api/test_cyc_family_details.py
> +@pytest.mark.asyncio
Change to `@pytest_asyncio.fixture`

2024-03-03 09:31 UTC, alvgonfri commented on tests/api/test_cyc_family_details.py
> +import pytest
Change to `pytest_asyncio`

2024-03-03 09:31 UTC, alvgonfri commented on tests/api/test_cyc_family_details.py
> +    assert response.json() == create_family.model_dump()
I think this is not going to work. Maybe you could compare `response.json()` to the json you expect to be returned.

2024-03-03 09:31 UTC, alvgonfri commented on tests/api/test_cyc_family_details.py
> +        "members": [
This is not how you create a person. You must use the `Person.create` method as you did when creating a Family, indicating the "family_id". The "members" attribute must disappear from `family_data`.

2024-03-03 09:36 UTC, alvgonfri commented on tests/api/test_cyc_family_details.py
> +        "members": [
These are the lines I'm talking about:
![image](https://github.com/ISPP-07/backend/assets/73192598/b763d061-adbf-4c70-a013-c8837e74c12b)

2024-03-04 10:36 UTC, jmartinacu approved these changes
Ok

2024-03-04 10:41 UTC, alvarobernal2412 approved these changes
Perfect!

2024-03-04 10:45 UTC, merged