feat: API call for appointmet creation
ISPP-07/backend pull request #57
Opened 2024-02-29 11:49 UTC by davidg43

## Description
Create method for appointment creation is now available! It has relationship with Patient and Technician, those relations are managed successfully on appointment service.

# # Related Issue(s)
- #42 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @alvgonfri 
- @jmartinacu 

## Screenshots (if applicable)
![image](https://github.com/ISPP-07/backend/assets/80384087/f0094199-11bb-4a93-ba52-9d9720b2145e)

## Notes (if applicable)

2024-02-29 18:38 UTC, jmartinacu requested changes
The code has errors

<img width="754" alt="image" src="https://github.com/ISPP-07/backend/assets/99323099/fba12be1-7f65-4752-84f6-8ecea00ef1c7">

2024-02-29 18:38 UTC, jmartinacu commented on src/modules/acat/appointment/service.py
Our router, controller and service structure. It is designed so that the services do not call each other; it is the controllers that call the services they need. And in this code it is the service that is using the other defined services.
The controller should be importing the services not the service using others services.

2024-02-29 18:38 UTC, jmartinacu commented on src/modules/acat/appointment/service.py
> +    technician = await get_technician_by_id(session, appointment.technician_id)
There is a bug in the code, when the technician associated with the technician_id passed to the endpoint doesn't exist. You should check that the technician variable is not None, and if it is None you should abort the endpoint and return and 404 not found error to the endpoint user. 
This also has to be done with the patient.

2024-03-01 13:34 UTC, davidg43 commented
I just checked the config.py file and realized I don't have the latest version since the pull request was created after I started my task. If @gonzcm approves, I'll include this file in my own pull request to run the tests and avoid encountering new problems during the merge.

2024-03-01 15:55 UTC, alvgonfri commented on tests/api/test_acat_appointment_creation.py
> +    await Technician.create(session, **technician_data)
The feature works correctly, but there are some problems with the tests. I think you must create an user before creating a technician inside the test function.
![image](https://github.com/ISPP-07/backend/assets/73192598/541f4f00-5b0c-41d5-8d22-e73180e130db)

2024-03-01 16:58 UTC, Thealean28 commented on tests/api/test_acat_appointment_creation.py
> +    await Technician.create(session, **technician_data)
Done! Now it works correctly.

2024-03-01 23:27 UTC, alvgonfri approved these changes
Everything looks fine now!

2024-03-02 09:56 UTC, jmartinacu approved these changes
Everything  is correct

2024-03-02 09:59 UTC, merged